# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the Docker container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application's dependencies
RUN npm install

# Copy the rest of the application's code to the working directory
COPY . .

# Build the application
RUN npm run build

# Expose port 4000
EXPOSE 4000

# Start the application
CMD [ "npm", "start" ]