// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice = CardItemsSlice | NavbarSlice | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Primary content in *CardItems → Items*
 */
export interface CardItemsSliceDefaultItem {
  /**
   * Screenshot field in *CardItems → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_items.items[].screenshot
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  screenshot: prismic.ImageField<never>;

  /**
   * Help Center Link field in *CardItems → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: card_items.items[].help_center_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  help_center_link: prismic.LinkField;

  /**
   * Website Page Link field in *CardItems → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: card_items.items[].website_page_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  website_page_link: prismic.LinkField;

  /**
   * Website Title field in *CardItems → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_items.items[].website_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  website_title: prismic.KeyTextField;

  /**
   * Website Description field in *CardItems → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_items.items[].website_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  website_description: prismic.KeyTextField;
}

/**
 * Card Items Featured variation for CardItems Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardItemsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<CardItemsSliceDefaultItem>
>;

/**
 * Primary content in *CardItems → Items*
 */
export interface CardItemsSliceCardItemsNotFeaturedItem {
  /**
   * Screenshot field in *CardItems → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_items.items[].screenshot
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  screenshot: prismic.ImageField<never>;

  /**
   * Help Center Link field in *CardItems → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: card_items.items[].help_center_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  help_center_link: prismic.LinkField;

  /**
   * Website Page Link field in *CardItems → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: card_items.items[].website_page_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  website_page_link: prismic.LinkField;

  /**
   * Website Title field in *CardItems → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_items.items[].website_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  website_title: prismic.KeyTextField;

  /**
   * Website Description field in *CardItems → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_items.items[].website_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  website_description: prismic.KeyTextField;
}

/**
 * Card Items Not Featured variation for CardItems Slice
 *
 * - **API ID**: `cardItemsNotFeatured`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardItemsSliceCardItemsNotFeatured = prismic.SharedSliceVariation<
  "cardItemsNotFeatured",
  Record<string, never>,
  Simplify<CardItemsSliceCardItemsNotFeaturedItem>
>;

/**
 * Slice variation for *CardItems*
 */
type CardItemsSliceVariation =
  | CardItemsSliceDefault
  | CardItemsSliceCardItemsNotFeatured;

/**
 * CardItems Shared Slice
 *
 * - **API ID**: `card_items`
 * - **Description**: CardItems
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardItemsSlice = prismic.SharedSlice<
  "card_items",
  CardItemsSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultItem {
  /**
   * Tag Link field in *Hero → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].tag_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tag_link: prismic.LinkField;

  /**
   * Tag Name field in *Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].tag_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag_name: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  Simplify<HeroSliceDefaultItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Navbar → Default → Primary*
 */
export interface NavbarSliceDefaultPrimary {
  /**
   * Logo Link field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.logo_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  logo_link: prismic.LinkField;

  /**
   * Logo Image field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.logo_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_image: prismic.ImageField<never>;

  /**
   * Logo Text field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.logo_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  logo_text: prismic.KeyTextField;

  /**
   * Buy me a coffee link field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.buy_me_a_coffee_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buy_me_a_coffee_link: prismic.LinkField;

  /**
   * Buy me a coffee text field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.buy_me_a_coffee_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buy_me_a_coffee_text: prismic.KeyTextField;

  /**
   * Submit a site link field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.submit_a_site_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  submit_a_site_link: prismic.LinkField;

  /**
   * Submit a site text field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.submit_a_site_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  submit_a_site_text: prismic.KeyTextField;
}

/**
 * Default variation for Navbar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavbarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavbarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Navbar*
 */
type NavbarSliceVariation = NavbarSliceDefault;

/**
 * Navbar Shared Slice
 *
 * - **API ID**: `navbar`
 * - **Description**: Navbar
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavbarSlice = prismic.SharedSlice<"navbar", NavbarSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CardItemsSlice,
      CardItemsSliceDefaultItem,
      CardItemsSliceCardItemsNotFeaturedItem,
      CardItemsSliceVariation,
      CardItemsSliceDefault,
      CardItemsSliceCardItemsNotFeatured,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefaultItem,
      HeroSliceVariation,
      HeroSliceDefault,
      NavbarSlice,
      NavbarSliceDefaultPrimary,
      NavbarSliceVariation,
      NavbarSliceDefault,
    };
  }
}
