// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  card_items: dynamic(() => import("./CardItems")),
  hero: dynamic(() => import("./Hero")),
  privacy_policy: dynamic(() => import("./PrivacyPolicy")),
};
