// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  card_items: dynamic(() => import("./CardItems")),
  hero: dynamic(() => import("./Hero")),
  navbar: dynamic(() => import("./Navbar")),
};
